SET DEFINE OFF;
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('30873490S', 'RAUL', 'BELTRAN', 'ANSON', TO_DATE('12/10/1977 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '976145625', 'rbeltran@aragon.es', 'ZARAGOZA', 'HOMBRE', 2, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('89491751Q', 'ANA ISABEL', 'BUEN', 'ABOS', TO_DATE('05/04/1974 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '657454812', 'aibuena@aragon.es', 'ZARAGOZA', 'MUJER', 0, 
    'SOLTERO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('47923801N', 'ANGEL LUIS', 'CABELLO', 'GUILLEN', TO_DATE('01/01/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '655894213', 'alcabellog@salud.aragon.es', 'ZARAGOZA', 'HOMBRE', 3, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('38195496V', 'MARIA PILAR', 'CARAZO', 'LACRUZ', TO_DATE('05/04/1974 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '854782365', 'pcarazo@aragon.es', 'ZARAGOZA', 'MUJER', 1, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('19709864Z', 'MARIA VICTORIA', 'CORONAS', 'PUYUELO', TO_DATE('12/07/1957 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '876382747', 'vcoronas@aragon.es', 'ZARAGOZA', 'MUJER', 2, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('88255600T', 'SANTIAGO', 'ESTEVAN', 'BARINGO', TO_DATE('07/05/1967 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'sestevan@aragon.es', 'ZARAGOZA', 'HOMBRE', 1, 
    'SOLTERO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('19120080L', 'ALBERTO', 'GARCIA', 'HERRERO', TO_DATE('02/04/1979 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '676858594', 'agarciahe@aragon.es', 'ZARAGOZA', 'HOMBRE', 2, 
    'SOLTERO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('11152178F', 'ELISA MARIA', 'GARCIA', 'MESA', TO_DATE('12/07/1957 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'emgarcia@aragon.es', 'ZARAGOZA', 'MUJER', 3, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('07788941Z', 'MARIA', 'GUILLEN', 'CASTILLO', TO_DATE('09/08/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'mguillen@aragon.es', 'ZARAGOZA', 'MUJER', 0, 
    'SOLTERO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('09140649N', 'JAVIER', 'IRANZO', 'BURRIEL', TO_DATE('07/05/1967 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '646588589', 'jiranzo@aragon.es', 'ZARAGOZA', 'HOMBRE', 1, 
    'SOLTERO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('89251064R', 'PORFIRIO', 'IZQUIERDO', 'AGUADO', TO_DATE('02/04/1979 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'pizquierdoa@aragon.es', 'ZARAGOZA', 'HOMBRE', 1, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('55796792B', 'JOAQUIN', 'MAICAS', 'ALIJARDE', TO_DATE('01/01/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '657495949', 'jmaicas@aragon.es', 'ZARAGOZA', 'HOMBRE', 2, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('80836011G', 'VICTOR', 'MARTIN', 'GOYENECHE', TO_DATE('09/08/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'vmarting@aragon.es', 'ZARAGOZA', 'MUJER', 3, 
    'SOLTERO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('75227150S', 'PILAR', 'MORA', 'FRANCO', TO_DATE('01/01/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'mpmora@aragon.es', 'ZARAGOZA', 'MUJER', 2, 
    'SOLTERO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('30717602K', 'RAUL', 'PERALES', 'JIMENEZ', TO_DATE('04/07/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'rperales@aragon.es', 'ZARAGOZA', 'HOMBRE', 0, 
    'SOLTERO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('45096449G', 'DAVID', 'PEREZ', 'ARANDA', TO_DATE('09/08/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '654342323', 'dpereza@aragon.es', 'ZARAGOZA', 'HOMBRE', 1, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('02517669C', 'MARIA PILAR', 'PEREZ', 'GOMEZ', TO_DATE('07/04/1983 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '657875423', 'borrame@aragon.es', 'ZARAGOZA', 'MUJER', 1, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('42982635M', 'JESUS ALBERTO', 'PINEDO', 'LUQUE', TO_DATE('02/04/1979 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'japinedo@aragon.es', 'ZARAGOZA', 'HOMBRE', 2, 
    'SOLTERO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('59576150D', 'CAROLINA', 'PUYUELO', 'MUNIESA', TO_DATE('07/04/1983 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'cpuyuelom@aragon.es', 'ZARAGOZA', 'MUJER', 2, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('74714505V', 'SERGIO', 'SANCHEZ-VALVERDE', 'LAHERA', TO_DATE('07/05/1967 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '976345768', 'ssanchezvalverde@aragon.es', 'ZARAGOZA', 'HOMBRE', 3, 
    'SOLTERO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('43181858W', 'DAVID', 'TORREA', 'GARCES', TO_DATE('07/04/1983 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'dtorrea@aragon.es', 'ZARAGOZA', 'HOMBRE', 1, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('59289864G', 'SERGIO', 'CASTRO', 'OYAGA', TO_DATE('09/08/1975 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'scastroo@aragon.es', 'HUESCA', 'HOMBRE', 2, 
    'SOLTERO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('69775226B', 'EDUARDO', 'ALEGRE', 'GOMEZ', TO_DATE('02/04/1979 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '978521452', 'ealegreg@aragon.es', 'TERUEL', 'HOMBRE', 1, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('23077532E', 'SEBASTIAN JOSE', 'AVELLANA', 'RAMIZ', TO_DATE('07/05/1967 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'sjavellana@aragon.es', 'TERUEL', 'HOMBRE', 2, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('04486880V', 'EMILIA', 'BUJ', 'GARGALLO', TO_DATE('01/01/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'ebuj@aragon.es', 'TERUEL', 'MUJER', 3, 
    'SOLTERO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('62327793R', 'ANTONIO', 'FANDOS', 'SANCHEZ', TO_DATE('02/04/1979 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    '655214785', 'afandoss@aragon.es', 'TERUEL', 'HOMBRE', 1, 
    'CASADO');
Insert into ALUMNO
   (NIF, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, 
    TELEFONO, EMAIL, LOCALIDAD, SEXO, NUM_HIJOS, 
    ESTADO_CIVIL)
 Values
   ('09325379Y', 'MARIA DOLORES', 'TORRES', 'ARANDA', TO_DATE('07/05/1967 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, 'mdtorres@aragon.es', 'TERUEL', 'MUJER', 0, 
    'SOLTERO');
COMMIT;
