CREATE TABLE ALUMNO
(
  NIF               VARCHAR2(50 BYTE),
  NOMBRE            VARCHAR2(50 BYTE),
  APELLIDO1         VARCHAR2(50 BYTE),
  APELLIDO2         VARCHAR2(50 BYTE),
  FECHA_NACIMIENTO  DATE,
  TELEFONO          VARCHAR2(50 BYTE),
  EMAIL             VARCHAR2(50 BYTE),
  LOCALIDAD         VARCHAR2(50 BYTE),
  SEXO              VARCHAR2(50 BYTE),
  NUM_HIJOS         NUMBER(2),
  ESTADO_CIVIL      VARCHAR2(50 BYTE)
);

COMMENT ON TABLE ALUMNO IS 'Tabla con los datos del alumno';

COMMENT ON COLUMN ALUMNO.NIF IS 'Nif';

COMMENT ON COLUMN ALUMNO.NOMBRE IS 'Nombre';

COMMENT ON COLUMN ALUMNO.APELLIDO1 IS 'Apellido1';

COMMENT ON COLUMN ALUMNO.APELLIDO2 IS 'Apellido2';

COMMENT ON COLUMN ALUMNO.FECHA_NACIMIENTO IS 'Fecha de nacimiento';

COMMENT ON COLUMN ALUMNO.TELEFONO IS 'Teléfono';

COMMENT ON COLUMN ALUMNO.EMAIL IS 'Email';


CREATE TABLE CURSO
(
  ID_CURSO      NUMBER(4),
  NOMBRE        VARCHAR2(255 BYTE),
  HORAS         NUMBER(3),
  FECHA_INICIO  DATE,
  FECHA_FIN     DATE
);

COMMENT ON TABLE CURSO IS 'Tabla con los datos del curso';

COMMENT ON COLUMN CURSO.ID_CURSO IS 'Id. curso';

COMMENT ON COLUMN CURSO.NOMBRE IS 'Nombre del curso';

COMMENT ON COLUMN CURSO.HORAS IS 'Horas';

COMMENT ON COLUMN CURSO.FECHA_INICIO IS 'Fecha de inicio';


CREATE TABLE CURSO_ALUMNO
(
  ID_CURSO         NUMBER(4),
  NIF              VARCHAR2(50 BYTE),
  FECHA_MATRICULA  DATE,
  CALIFICACION     NUMBER(4,2)
);

COMMENT ON TABLE CURSO_ALUMNO IS 'Tabla que mantiene los alumnos de un curso';

COMMENT ON COLUMN CURSO_ALUMNO.ID_CURSO IS 'Id. curso';

COMMENT ON COLUMN CURSO_ALUMNO.NIF IS 'Nif del alumno';

COMMENT ON COLUMN CURSO_ALUMNO.FECHA_MATRICULA IS 'Fecha de matrícula';

COMMENT ON COLUMN CURSO_ALUMNO.CALIFICACION IS 'Calificación final';


CREATE TABLE CURSO_ASIGNATURA
(
  ID_CURSO       NUMBER(4),
  ID_ASIGNATURA  NUMBER(4),
  NOMBRE         VARCHAR2(255 BYTE)
);

COMMENT ON TABLE CURSO_ASIGNATURA IS 'Datos de las asignaturas de un curso';

COMMENT ON COLUMN CURSO_ASIGNATURA.ID_CURSO IS 'Id. curso';

COMMENT ON COLUMN CURSO_ASIGNATURA.ID_ASIGNATURA IS 'Id. asignatura';

COMMENT ON COLUMN CURSO_ASIGNATURA.NOMBRE IS 'Nombre de la asignatura';


CREATE TABLE CURSO_ASIGNATURA_ALUMNO
(
  ID_CURSO       NUMBER(4),
  ID_ASIGNATURA  NUMBER(4),
  NIF            VARCHAR2(50 BYTE),
  NOTA           NUMBER(4,2),
  OBSERVACIONES  VARCHAR2(4000 BYTE)
);

COMMENT ON TABLE CURSO_ASIGNATURA_ALUMNO IS 'Tabla que mantiene los datos de un alumno en una asignatura del curso';

COMMENT ON COLUMN CURSO_ASIGNATURA_ALUMNO.ID_CURSO IS 'Id. curso';

COMMENT ON COLUMN CURSO_ASIGNATURA_ALUMNO.ID_ASIGNATURA IS 'Id. asignatura';

COMMENT ON COLUMN CURSO_ASIGNATURA_ALUMNO.NIF IS 'Nif';

COMMENT ON COLUMN CURSO_ASIGNATURA_ALUMNO.NOTA IS 'Nota';

COMMENT ON COLUMN CURSO_ASIGNATURA_ALUMNO.OBSERVACIONES IS 'Observaciones';


CREATE UNIQUE INDEX ALUMNO_PK ON ALUMNO
(NIF);

CREATE UNIQUE INDEX CURSO_ALUMNO_PK ON CURSO_ALUMNO
(ID_CURSO, NIF);

CREATE UNIQUE INDEX CURSO_ASIGNATURA_ALUMNO_PK ON CURSO_ASIGNATURA_ALUMNO
(ID_CURSO, NIF, ID_ASIGNATURA);

CREATE UNIQUE INDEX CURSO_ASIGNATURA_PK ON CURSO_ASIGNATURA
(ID_CURSO, ID_ASIGNATURA);

CREATE UNIQUE INDEX CURSO_PK ON CURSO
(ID_CURSO);

ALTER TABLE ALUMNO ADD (
  CONSTRAINT ALUMNO_PK
  PRIMARY KEY
  (NIF)
  USING INDEX ALUMNO_PK
  ENABLE VALIDATE);

ALTER TABLE CURSO ADD (
  CONSTRAINT CURSO_PK
  PRIMARY KEY
  (ID_CURSO)
  USING INDEX CURSO_PK
  ENABLE VALIDATE);

ALTER TABLE CURSO_ALUMNO ADD (
  CONSTRAINT CURSO_ALUMNO_PK
  PRIMARY KEY
  (ID_CURSO, NIF)
  USING INDEX CURSO_ALUMNO_PK
  ENABLE VALIDATE);

ALTER TABLE CURSO_ASIGNATURA ADD (
  CONSTRAINT CURSO_ASIGNATURA_PK
  PRIMARY KEY
  (ID_CURSO, ID_ASIGNATURA)
  USING INDEX CURSO_ASIGNATURA_PK
  ENABLE VALIDATE);

ALTER TABLE CURSO_ASIGNATURA_ALUMNO ADD (
  CONSTRAINT CURSO_ASIGNATURA_ALUMNO_PK
  PRIMARY KEY
  (ID_CURSO, NIF, ID_ASIGNATURA)
  USING INDEX CURSO_ASIGNATURA_ALUMNO_PK
  ENABLE VALIDATE);

ALTER TABLE CURSO_ALUMNO ADD (
  CONSTRAINT CURSO_ALUMNO_R01 
  FOREIGN KEY (ID_CURSO) 
  REFERENCES CURSO (ID_CURSO)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT CURSO_ALUMNO_R02 
  FOREIGN KEY (NIF) 
  REFERENCES ALUMNO (NIF)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE CURSO_ASIGNATURA ADD (
  CONSTRAINT CURSO_ASIGNATURA_R01 
  FOREIGN KEY (ID_CURSO) 
  REFERENCES CURSO (ID_CURSO)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE CURSO_ASIGNATURA_ALUMNO ADD (
  CONSTRAINT CURSO_ASIGNATURA_ALUMNO_R01 
  FOREIGN KEY (ID_CURSO, ID_ASIGNATURA) 
  REFERENCES CURSO_ASIGNATURA (ID_CURSO,ID_ASIGNATURA)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT CURSO_ASIGNATURA_ALUMNO_R02 
  FOREIGN KEY (NIF) 
  REFERENCES ALUMNO (NIF)
  ON DELETE CASCADE
  ENABLE VALIDATE);
